server:
  port: 5003
spring:
  profiles:
    active: base
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/sba?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost